#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
echo "Configuration contract available: $ROOT/spec/harness/configuration-contract.yaml"
echo "Secrets values are not displayed or generated by this command."
