#!/usr/bin/env bash
set -euo pipefail

FROM="${FROM_STATE:-}"
TO="${TO_STATE:-}"

case "$FROM:$TO" in
  PLANNED:ANALYZING|ANALYZING:SPEC_READY|SPEC_READY:IMPLEMENTING|IMPLEMENTING:TESTING|TESTING:SECURITY_REVIEW|SECURITY_REVIEW:ARCHITECTURE_REVIEW|ARCHITECTURE_REVIEW:READY_FOR_REVIEW|READY_FOR_REVIEW:APPROVED|APPROVED:MERGED|MERGED:DEPLOYED|DEPLOYED:VERIFIED|VERIFIED:OPERATE)
    echo "Transition allowed: $FROM -> $TO"
    ;;
  *)
    echo "Transition denied: $FROM -> $TO"
    exit 3
    ;;
esac
